name: Deploy on server stage

env:
  APP_ENV: ${{ secrets.STAGING }}
  NAME: todo-list-website

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3

      - name: Extract env file multi line.
        run: |
          rm -r -f .env
          touch .env_temp
          echo $APP_ENV | tee .env_temp
          sed 's/ /\n/g' .env_temp >> .env
          rm -r -f .env_temp

      - name: Docker
        run: |
          docker build -t $NAME .
          docker save -o $NAME.tar $NAME

      - name: Copy Docker image to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.STAGE_SERVER_KEY_SSH }}
          source: "$NAME.tar,docker-compose.yml"
          target: "~/$NAME"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.STAGE_SERVER_KEY_SSH }}
          script: |
            cd ~/$NAME
            sudo snap install docker
            sudo docker load --input $NAME.tar
            sudo docker-compose up -d --force-recreate
