name: Test Slack Notification

on:
  push:
    branches: ["test-slack"]

jobs:
  build:
    name: "Test Slack Notification"
    runs-on: ubuntu-latest

    steps:
      - name: Post build result to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C053HR3MDQB"
          slack-message: "<b>ABC</b>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()
